### ISSUE TITLE
Feature: Add an alert to web app if grill is alarming from flame-out or some other cause.

### ISSUE THREAD

**Issue by muxall** [muxall/RPTCQ-LCD#14]
Feature: Add an alert to web app if grill is alarming from flame-out or some other cause.

**Comment by muxall** [comment]
Here is a javascript solution.  I'm not sure we have enough memory for it.
var snd = new Audio("beep.wav"); // buffers automatically when created
snd.play();

**Comment by muxall** [comment]
The web app should beep when:
1. 4x The grill changes state to cool down.
2. 1x The ADC is reset.
3. 4x The grill flame-out detection changes to Pause state.

**Comment by muxall** [comment]
Flame-out detect:
1. Set Flame-out detect time to 5 minutes; click save.
2. Set Profile 1 to 225F cook time 10 minutes. Un-check Hold.
3. Set Profile 2 to 180F. Check Hold.
4. Click Enter/Save.
5. Click Start.
6. Start the graph.
The flame-out detect should alarm when dropping from 225 to 180.

**Comment by kennethLeeHarris** [comment]
On the flame-out detection change to pause state. It did not beep four times. It beeped every other second on the laptop and controller to I hit the start button. For cool down it did beep four times before starting.
