### ISSUE TITLE
Trapezoid: Issues that need to be fixed.

### ISSUE THREAD

**Issue by muxall** [muxall/RPTCQ-LCD#156]
0. Button panel PCB layout headers need to be flipped top to bottom.
1. Ring around button header holes are not large enough.
2. Grinding button headers cuts into PCB traces and flood-fill.
3. Jack panel cutout in faceplate is too small.  Cannot see ON/OFF and jack number labels.
4. Faceplate is larger than Z-Grills faceplate.  Not sure how that happened.
5. The 3 incorrect mounting holes need to be covered up and 2 mounting holes added in the correct spots.

**Comment by PhilSmith46** [comment]
Can you shoot me some pics via email?

**Comment by muxall** [comment]
I’ll make a video when I get a chance.  I was out of town last week and with the holiday, I’m a bit backed up.

**Comment by muxall** [comment]
BTW, they aren’t design flaws but errors with the CAD drawing that I need to fix.  It’s like a TTD.  The video will be a status report.  The biggest problem is the button panel pcb needs to be re-spun… ugh!

 

From: ***@***.*** ***@***.***> 
Sent: Tuesday, July 5, 2022 1:03 PM
To: 'muxall/RPTCQ-LCD' ***@***.***>
Subject: RE: [muxall/RPTCQ-LCD] Trapezoid: Design flaws that need to be fixed. (Issue #156)

 

I’ll make a video when I get a chance.  I was out of town last week and with the holiday, I’m a bit backed up.

**Comment by PhilSmith46** [comment]
If anyone can correct it, it will be you!

**Comment by muxall** [comment]
Fixed by Michael Crane 5/23/2023
