### ISSUE TITLE
Feature: Enable mDNS

### ISSUE THREAD

**Issue by muxall** [muxall/RPTCQ-LCD#33]
isMDNS

**Comment by muxall** [comment]
Enabled mDNS in 0.541.
NOTE: mDNS only works on Windows, Apple products, and Linux.  It does not work on Android devices using Chrome.  Must have https://support.apple.com/kb/DL999 for Windows 7
To test: 
1. Enter http://probbq.local into the web browser address bar.  Verify the you are able to login to the controller.
2. Verify the ability to change the "Controller Name" in the config tab.
3. Verify the user is prompted to reboot the controller.

**Comment by kennethLeeHarris** [comment]
I test this out today in version 0.451S. on Firefox, Chrome, my iPhone and the Microsoft tablet. All four worked no problems at all.
