### ISSUE TITLE
Issue: Auger duty cycle 30:30 is not accurate.

### ISSUE THREAD

**Issue by muxall** [muxall/RPTCQ-LCD#35]
starting at 3:29 on the video I measured the following: on for 27, off for 23, on for 16, off for 18 on for 28, then the video cuts to later in the warm up, and starting at 4:39 I see on for 32 off for 30 on for 18 and then the test ends.

**Comment by kennethLeeHarris** [comment]
I test out the auger and my results were auger on for 31 sec. off for 30 sec. for just over 4 minutes
