### ISSUE TITLE
Issue: Graph Tab; Please Login pops up after Clear then Refresh.

### ISSUE THREAD

**Issue by muxall** [muxall/RPTCQ-LCD#38]
Issue: Graph Tab; clicking Clear then Refresh make a "Must Login" pop up if the user tries to ad a new Tab.

Work Around: Clicking submit on Control tab will allow the user to add a new tab without losing data.

**Comment by kennethLeeHarris** [comment]
Just tested it on 0.506s. It tested great, No pop ups came up after hitting clear then refresh.
