### ISSUE TITLE
Pellet hopper fill level bar gauge does not read 10% when set.

### ISSUE THREAD

**Issue by muxall** [muxall/RPTCQ-LCD#43]
Set the pellet hopper fill level to 10%.  The bar gauge displays much less than 10%

**Comment by muxall** [comment]
Fixed in 0.450

**Comment by kennethLeeHarris** [comment]
I update to 0.450 The pellet hopper fill level bar gauge does say 10% now. Not just that but it also  lines up correctly with all of the numbers now.
