### ISSUE TITLE
Issue: Updating Cook-By-Probe targetProbeTemp from LCD does not update web app

### ISSUE THREAD

**Issue by muxall** [muxall/RPTCQ-LCD#48]

**Comment by muxall** [comment]
Made a lot of changes to processOkGetData.  May need to make a copy of scanProbeCook for inbound configs.

**Comment by kennethLeeHarris** [comment]
I changed the Cook-By-Probe Target Temp on the controller and it would update in the web app in Ending Control but not in Cook State.
