### ISSUE TITLE
Feature: Add Pop-up alert w/ Warm-Up Bypass enabled in GUI

### ISSUE THREAD

**Issue by muxall** [muxall/RPTCQ-LCD#5]

**Comment by muxall** [comment]
Fixed on 0.450
Verify pop-up message alerts the user if Bypass Warm Up State is checked in the config tab and the web app beeps 4 times.
Also, verify the controller beeps 4 times and displays WarmUp ByPass on LCD status screen.

**Comment by kennethLeeHarris** [comment]
I tested it in 0.450s and it works great. The pop-up message does come up right after hitting start it says "bypass warm-up state set in config! The igniter is disabled." I hit ok it beeps four times on the controller. Right before it tells you "BBQ on command sent." You hit ok and it beeps four times on the laptop. It does display WarmUp ByPass on LCD status screen.
