### ISSUE TITLE
Issue: Setting Profile 2 Hold checked went to cool down state and didn't hold.

### ISSUE THREAD

**Issue by muxall** [muxall/RPTCQ-LCD#51]
Issue: Setting Profile 1 to 10 minutes @ 180F no Hold and Profile 2 to 0 minutes @ 225F with Hold checked, using the front panel on the controller, went to cool down state and didn't hold.

**Comment by kennethLeeHarris** [comment]
After seeing Carter's video I don't know what he did because I had no problems. I tested it out on version 0.449. Profile 2 held for me no problems at all.
