### ISSUE TITLE
Issue: Crash caused by Chrome allowing page reload while current page iFrame is loading.

### ISSUE THREAD

**Issue by muxall** [muxall/RPTCQ-LCD#57]
Crash caused by Chrome allowing page reload while current page iFrame is loading. This overloads the ESP32 and causes it to crash.
To reproduce this issue: Using the web app, login to the controller.  Click on config tab.  While config tab is loading, do a page reload using the circle-arrow next to address bar.  It may take a few times.  This may be caused by Chrome's Lazy-Loading feature.

Work-around: Firefox does not allow page reload while an iFrame is loading.

**Comment by muxall** [comment]
Added a page cache with a max-age of 10 minutes to prevent user from chrome from pounding the controller with GET requests.

**Comment by kennethLeeHarris** [comment]
I test this out today in version 0.451S. It is still crashing, I know you are working on it right now. I just wrote this that way you know I test it out today.

**Comment by kennethLeeHarris** [comment]
I tested it out today in v0.502. I tried to crash it in chrome for about 15 minutes no luck.
