### ISSUE TITLE
Issue: Login to controller from multiple devices.

### ISSUE THREAD

**Issue by muxall** [muxall/RPTCQ-LCD#58]
The controller should accept or reject login from multiple devices depending on load.
To test: Use a phone, tablet and pc.  Login from each device and verify the controller handles the connections or rejects one or two connections if it is too busy.  It should not crash!

**Comment by kennethLeeHarris** [comment]
The Controller accept all three devices. No crashing with my phone, tablet and laptop all work with no problems.
