### ISSUE TITLE
Test: Spin knob 6-7 times while scrolling through wifi ssids.

### ISSUE THREAD

**Issue by muxall** [muxall/RPTCQ-LCD#6]

**Comment by Cappypoo** [comment]
I believe this has been solved  with the board sliding out of the pin header due to the zip tie

**Comment by muxall** [comment]
> I believe this has been solved with the board sliding out of the pin header due to the zip tie

Okay, I'll close this issue for now and re-open if we see it again.  Thanks for the update.
