### ISSUE TITLE
Issue: Web page refresh after letting the web page go stale caused the controller to reboot.

### ISSUE THREAD

**Issue by muxall** [muxall/RPTCQ-LCD#64]
Using Chrome, load up the controller web app and let it sit for 10 minutes to 2 days.  Afterwards, click page reload, circle arrow, and the controller will restart.

It was noticed the controller doesn't have to be on for the stale chrome refresh to cause it to reboot.

**Comment by muxall** [comment]
I think it is fixed in 0.451.

**Comment by muxall** [comment]
I think it is fixed in 0.451.

**Comment by kennethLeeHarris** [comment]
I test this out three times today in version 0.451S. I did 45 minutes 30 minutes and 10 minutes test. all three times I had no problems at all.
