### ISSUE TITLE
Issue: Long ssids caused controller to crash.

### ISSUE THREAD

**Issue by muxall** [muxall/RPTCQ-LCD#67]
Added support for 64 char SSIDs just in case some routers or equipment allow longer than 32 char SSIDs, which is the standard.
Test: Verify 32 char SSID works okay.

**Comment by muxall** [comment]
Fixed in 0.503d tested by Carter.  Ported to 0.504.
Notes - changed char limit 64 to 33.  Espressif chip only supports 31 char SSIDs.  There is a limit of 32 char password with /0 so 31 char password because of a mistake in the EEPROM initialization.  To fix this would require reformatting the EEPROM and everyone would have to re-enter their custom information.

**Comment by kennethLeeHarris** [comment]
It looks like you and Carter already fix this for the most part. I'm not going to market as pass to I talk to you.
