### ISSUE TITLE
Issue: Web App: "Please Login" popped up even though the user was already logged in.

### ISSUE THREAD

**Issue by muxall** [muxall/RPTCQ-LCD#71]
This is different from the user clearing the graph issue.  Maybe multiple clients logged in?

**Comment by muxall** [comment]
Fixed in 0.505

**Comment by kennethLeeHarris** [comment]
Tested it on 0.506s. I have been running a lot of test these last few days. I haven't seen any please login pop-ups once I was already logged in.
